---
name: hsp2_py38
channels:
    - conda-forge

dependencies:
    # Aligned with Anaconda 2021.05 (May 13, 2021)
    # package management
    - conda
    - conda-build
    - pip

    # Running HSP2
    - python =3.8*
    - scipy  # Scipy also installs numpy
    # Pandas installs most scientific Python modules, such as Numpy, etc.
    - pandas ==1.2.*
    - numba ==0.53.1
    - numpy ==1.20.*  # for compatibility with numba version <0.53
    # latest compatible with both versions of PyTables & h5py below
    # - doesn't work with setup.py
    - hdf5 ==1.10.6
    - pytables ==3.6.1
    - h5py >=3.1
    - hdf5plugin  # HDF5 compression filters for h5py & jupyterlab_hdf
    - cltoolbox

    # Interactivity & Visualization via Jupyter Notebooks
    # (optional, but required for tutorials)
    - jupyterlab ==3.0.*  #  also installs classic Jupyter notbook
    - ipympl  # jupyter-matplotlib, https://github.com/matplotlib/ipympl
    - nodejs  # required for many JupyterLab extensions
    # Conda environment & package access extension from within Jupyter
    - nb_conda
    # HoloViz, https://holoviz.org
    - hvplot  # hvPlot installs most HoloViz libs, including matplotlib
    - ipywidgets  # Required for HoloViz interactivity in Jupyter notebooks

    # Dev tools (optional)
    - python-language-server
    # Includes both the server extension (jupyter-lsp) and pyls third-party
    # server (python-language-server)
    - jupyter-lsp-python
    - jupyterlab-lsp  # Docs at https://github.com/krassowski/jupyterlab-lsp


    # PIP install requirements only if it is not possible with conda
    # https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#using-pip-in-an-environment
    # Optional, but recommended for tutorials
    - pip:
    # https://github.com/lckr/jupyterlab-variableInspector
    # - lckr-jupyterlab-variableinspector
    # Explore HDF5 files in JupyterLab. Requires an additional step to install.
    # - jupyterlab_hdf
    # Installation instructions:
    # https://github.com/jupyterlab/jupyterlab-hdf5#installation
