from pathlib import Path
import pandas as pd

_data_dir = Path(__file__).parent.parent.parent / "data"
_parameters = pd.read_csv(_data_dir / "Parameters.csv")
_tables = pd.read_csv(_data_dir / "Tables.csv")


def write_uci_parameters(outbasename, model, mode="w"):
    """Write a UCI file from a model dictionary."""

    block_order = {
        "GLOBAL": 1,
        "FILES": 2,
        "OPN SCHEMATIC": 3,
        "PERLND": 4,
        "IMPLND": 5,
        "RCHRES": 6,
        "MASS-LINK": 7,
        "NETWORK": 8,
    }

    sort_keys = sorted(model.keys(), key=lambda k: block_order.get(k[0], 99))

    blocks_written = set()
    inside_block = False
    table_name = ""
    table_num = ""
    with open(outbasename + ".uci", mode) as f:
        f.write("*** UCI file generated by hsp2 write_uci_parameters.py\n")
        f.write("RUN\n")
        for key in sort_keys:
            block_name = key[0]
            if len(key) in [2, 3]:
                table_name = key[1]
            if len(key) == 3:
                table_num = key[2]
            if block_name not in blocks_written:
                if inside_block:
                    f.write(f"END {prev_block_name}\n")
                inside_block = True
                f.write(f"{block_name}\n")
                blocks_written.add(block_name)
            prev_block_name = block_name
            f.write(f"  {table_name}{table_num}\n")
            table_info = _tables[
                (_tables["HSPF_BLOCK"] == block_name)
                & (
                    (_tables["HSPF_TABLE"] == table_name)
                    | (_tables["HSPF_TABLE"].isna())
                )
            ].convert_dtypes()
            f.write(f"{table_info['HELP']}\n")
            for index, row_items in model[key].iterrows():
                [f.write(f"{row_items[i]} ") for i in range(len(row_items))]
                f.write("\n")
            f.write(f"  END {table_name}{table_num}\n")

        f.write("# End of UCI file\n")
